### ISSUE TITLE
Unhandled exception in poller

### ISSUE THREAD

**Issue by krim404** [CyberDNS/Lupusec2Mqtt#25]
This is just a placeholder till i have more informations

```
[23:26:18 INF] Lupusec2Mqtt is starting up... {}
[23:26:18 INF] Polling... (Every 5th cycle is logged) {"SourceContext": "Lupusec2Mqtt.Lupusec.PollingHostedService"}
Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at Lupusec2Mqtt.Lupusec.PollingHostedService.PublishPowerSwitches() in /src/Lupusec2Mqtt/src/Lupusec2Mqtt/Lupusec/PollingHostedService.cs:line 134
   at Lupusec2Mqtt.Lupusec.PollingHostedService.DoWork(Object state) in /src/Lupusec2Mqtt/src/Lupusec2Mqtt/Lupusec/PollingHostedService.cs:line 115
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by krim404** [comment]
Seems like problem is only occuring in the non edge version. close
